# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '04.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1200, 600)
        Form.setMinimumSize(QtCore.QSize(1200, 600))
        Form.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(1200, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.export_data_btn = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.export_data_btn.setObjectName("export_data_btn")
        self.horizontalLayout_2.addWidget(self.export_data_btn)
        self.import_data_btn = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.import_data_btn.setStyleSheet("")
        self.import_data_btn.setObjectName("import_data_btn")
        self.horizontalLayout_2.addWidget(self.import_data_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_2.setMinimumSize(QtCore.QSize(500, 300))
        self.label_2.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setStyleSheet("background-color:grey;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 4, 4, 1)
        self.toolButton = QtWidgets.QToolButton(self.tabWidgetPage1)
        self.toolButton.setMaximumSize(QtCore.QSize(74, 16777215))
        self.toolButton.setStyleSheet("background-color:#5B9BD5;\n"
"color:white;\n"
"font-size:30px;\n"
"font-weight:900;")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 3, 3, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_1.setMinimumSize(QtCore.QSize(500, 400))
        self.label_1.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_1.setStyleSheet("background-color:grey;\n"
"")
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setIndent(0)
        self.label_1.setOpenExternalLinks(False)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 2, 0, 4, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.import_data_btn.clicked.connect(self.import_data_btn.show)
        self.export_data_btn.clicked.connect(self.export_data_btn.hide)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SWPU"))
        self.export_data_btn.setText(_translate("Form", "导出数据"))
        self.import_data_btn.setText(_translate("Form", "导入数据"))
        self.label_2.setText(_translate("Form", "数据未导入"))
        self.toolButton.setText(_translate("Form", "=>"))
        self.label_1.setText(_translate("Form", "数据未导入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("Form", "浅层地层破裂压力计算 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "钻井隔水导管极限承载力计算 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "隔水导管最小入泥深度 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "井口载荷分析及入泥深度推荐 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "隔水导管强度校核和稳定性分析 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "隔水导管轴向失稳临界载荷分析 "))

